Add help messages

diff --git a/goodnight b/goodnight
--- a/goodnight
+++ b/goodnight
@@ -6,8 +6,7 @@
 _goodnight () {
         local debug=false
 
-
-        # parse arguments
+        # arguments variables
         local action
         local -r stdout_default="log.out"
         local -r stderr_default="log.err"
@@ -18,11 +17,13 @@ _goodnight () {
         local stdin=$stdin_default
         local stderr_redirect=false
         local pid_to_wait=""
-        _parse_args "$@"
 
-        # read config
+        # config variables
         local recipient
         local -r config_file="$HOME/.goodnightrc"
+
+        # parse arguments and config
+        _parse_args "$@"
         _read_config "$config_file"
 
         # select mail command
@@ -63,8 +64,8 @@ _read_config () {
         # if the config file does not exist
         if ! [[ -f $config_file ]]
         then
-                touch $config_file
                 _error "No config file"
+                _help_config_file
                 exit 1
         fi
 
@@ -80,6 +81,7 @@ _read_config () {
                                 ;;
                         *) # error case
                                 _error "Invalid key '${key}' in config file"
+                                _help_config_file
                                 exit 1
                 esac
         done <$config_file
@@ -87,6 +89,7 @@ _read_config () {
         if [[ -z $recipient ]]
         then
                 _error "Recipient undefined in config file"
+                _help_config_file
                 exit 1
         fi
 
@@ -118,7 +121,11 @@ _parse_args () {
                                 pid_to_wait=$OPTARG
                                 ;;
                         h)
-                                echo help
+                                _help_command_line
+                                echo
+                                _help_extra
+                                echo
+                                _help_config_file
                                 exit 0
                                 ;;
                         d)
@@ -130,6 +137,7 @@ _parse_args () {
                                 ;;
                         *)
                                 _error "Unknown option '${option}'"
+                                _help_command_line
                                 exit 1
                                 ;;
                 esac
@@ -141,6 +149,7 @@ _parse_args () {
         if [[ -z $action ]]
         then
                 _error "No action specified"
+                _help_command_line
                 exit 1
         fi
 
@@ -151,6 +160,76 @@ _parse_args () {
 
         _debug "Action: $action"
         _debug "stdin: $stdin, stdout: $stdout, stderr: $stderr"
+}
+
+##
+# Print command line help
+#
+_help_command_line () {
+        cat << EOF
+goodnight [-o STDOUT] [-e STDERR | -E] [-i STDIN] [-w PID] [-h] [-d] COMMAND
+
+Bash tool to launch a disowned command that'll kindly send you a message when
+done. Like 'nohup my_command </dev/null >log 2>&1 &' but with a simpler
+interface and some fancy features.
+
+    COMMAND
+        Command to launch, with its own arguments.
+    -o STDOUT
+        Where to redirect the standard output to.
+        Default to '${stdout_default}'.
+    -e STDERR
+        Where to redirect the standard error to.
+        Default to '${stderr_default}'.
+    -E
+        Redirect the standard error to the standard output.
+        Do not set '-e' and '-E' at the same time.
+    -i STDIN
+        Where to redirect the standard input to.
+        Default to '${stdin_default}'.
+    -w PID
+        Wait for another command to finish befaure launching the provided one.
+        The command to wait is passed through its PID, which can be obtained
+        with 'ps' or by the second column of 'ps aux | grep
+        my_command_to_wait'.
+        More details in the following paragraph.
+    -h
+        Show this help and exit.
+    -d
+        Active debug mode. Increase verbosity.
+EOF
+}
+
+##
+# Print config file help
+#
+_help_config_file () {
+        cat << EOF
+Goodnight config file: '${config_file}' (must be created by the user)
+
+For now, the config file contains only one value: the address of the recipient.
+
+    recipient=person@example.com
+        Address where a mail is sent when the command has been finished.
+EOF
+}
+
+##
+# Print extra help
+#
+_help_extra () {
+        cat << EOF
+When invoking Goodnight with '-w', the command to wait must be running at the
+time Goodnight is called. To chain a command to another one which has been
+already invoked through 'goodnight -w some_other_command_pid', you can use this
+command's Goodnight's PID. The PID can be obtained with 'ps' or 'pstree -p'.
+Goodnight checks if the PID to wait exists every ${wait_pid_sleep} seconds.
+
+Goodnight can send you a mail when the command is terminated, wether
+successfuly or unsuccessfuly. It can use the 'sendmail' or the 'mail' command,
+depending on what is available on the host. You have to provide a mail address
+for this to work. This is set in the configuration file.
+EOF
 }
 
 ##
@@ -288,7 +367,7 @@ _debug () {
 # Show error line
 #
 _error () {
-        >&2 echo "$(tput sgr 0; tput bold)[$(tput setaf 1)ERROR$(tput setaf 9)] $@$(tput sgr 0)"
+        >&2 echo "$(tput sgr 0; tput bold)[$(tput setaf 1)ERROR$(tput setaf 7)] $@$(tput sgr 0)"
 }
 
 ##
